version: '3.8'

services:
  webhook:
    image: python:3.9
    container_name: tradingview_webhook
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=webhook.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    command: >
      sh -c "pip install flask requests && python webhook.py"
